### ISSUE TITLE
_settings.scss file is not being generated with build

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#64]
The auto-generated `_settings.scss` file is not being generated with the build

**Comment by soumak77** [comment]
@gakimball any idea how to get this working with octophant 1.0?  I'm getting the following error when I updated:

`Parser for annotation BaseApps not found`

I'm not sure where to define the required information

**Comment by soumak77** [comment]
@gakimball I figured it out, just need to manually update the files to the new format

**Comment by gakimball** [comment]
You need to use `octophant@0.1.0` to parse settings variables in that format. The older settings parser was manually parsing strings out of a Sass file. The newer version uses SassDoc.

[Here's the readme for the older settings parser.](https://github.com/zurb/octophant/tree/4db0a228b299fd080af60bce4b015d77d83d6e82) You need to change the delimiter from the default `@Foundation.settings`, so I think the setup is something like:

``` js
const octophant = return require('octophant');

gulp.task('settings', function() {
  octophant(['scss/components/*.scss'], {
    start: '/// @BaseApps.settings'
  });
});
```

[Here's what the newer formatting looks like.](https://github.com/zurb/foundation-sites/blob/develop/scss/_global.scss) We started that with Foundation 6 (and Foundation for Emails 2), and that's the format that `octophant@1.0.0` can process.

**Comment by soumak77** [comment]
@gakimball do you know if there is a way to get `octophant v1.0` to produce the same html partials that it did for `0.1.0`?  I like how the docs are configured to autoupdate the SCSS settings sections for each component and would like to get that working again.

Perhaps add a callback for each SCSS group being parsed so that those settings can be written to another file?  To make it more generic, possibly provide a transform function so that the settings can be manipulated if desired.  If you just want to do something with the settings without changing them (like print them to a file), the transform function can just be a pass-thru.

**Comment by gakimball** [comment]
I could, but I'm wary of continuing work on any of the libraries I worked on while I was at ZURB. I don't have much time in general, and I'm not supposed to be a ZURB admin still, they just haven't remembered to remove me yet.

That partials feature was removed because, for Foundation 6, we developed a more fully-formed solution for documentation: a tool called [Supercollider](https://github.com/zurb/supercollider). It's built for sites like the Foundation docs, which are more component-driven and implement documentation from multiple programming languages.

Now, setting it up takes a bit of work—right now, it has no default template (because we [custom wrote one](http://github.com/zurb/foundation-docs)).

_However_, I've forked Supercollider and intend to expand on it, because I think others could find it useful if it was easier to use out of the box. I almost have the Sass template ready, at which point I'll have something you can use.

If you have all of the Sass variables commented SassDoc-style (with three slashes and a `@type` annotation), we can recreate the same template functionality, and also possibly expand it into Angular. One plugin would be added to your build system, and you'd have a table of Sass variables appended to the bottom of each page with Sass.

``` js
return gulp.src(paths.html.templates)
    // update version throughout framework
    .pipe($.replace(/<version>/g, version))
    .pipe(spacedoc({
      adapters: ['sassdoc'],
      markdown: false,
      keepFm: true
    })
    .pipe(routes({
      path: 'build/assets/js/routes.js',
      root: 'docs'
    }))
    .pipe(gulp.dest('./build/templates'))
  ;
```

**Comment by soumak77** [comment]
@gakimball sounds great!  I'll manually update the SCSS templates for now until we can start using an automated solution.
