### ISSUE TITLE
Missing dependencies on npm?

### ISSUE THREAD

**Issue by Seb-** [base-apps/angular-base-apps#71]
I tried to install 2.0 with npm, and it seems no dependencies are coming with it?

With bower, it installs all of the required stuff such as fastclick, angular-ui-router, etc.

**Comment by soumak77** [comment]
That does bring up a good point.  The framework use to require both `npm` and `bower` to get all the dependencies setup.  `npm` was used to install the dynamic routing plugin, while `bower` was used to install the front-end dependencies.  Since the dynamic routing plugin was moved to it's own repository, there is no need to run both `npm install` and `bower install` anymore.  As such, the `npm` package can be updated to include the same dependencies as the `bower` package.
