### ISSUE TITLE
Add support for ui-router 1.0

### ISSUE THREAD

**Issue by Maximaximum** [base-apps/angular-base-apps#84]
I'd love to use some features of ui-router 1.0, which is currently in beta.

Here is a migration guide https://ui-router.github.io/guide/ng1/migrate-to-1_0

Not sure whether dependency on ui-router should be included into master, or it should be a separate branch?

**Comment by soumak77** [comment]
After refactoring the codebase for 2.0 and introducing https://github.com/base-apps/base-apps-router and https://github.com/base-apps/angular-dynamic-routing, I don't think there is a need to have `angular-ui-router` be a part of this project's `dependencies` anymore.  It should instead be moved to `devDependencies` since it is only needed by the docs and not the framework which is the key deliverable of the project.

With that said, I'm not sure there are any changes needed to this framework to support ui-router 1.0.  Perhaps this issue should be moved to one of the projects specified above?

I'll keep this issue open to address moving ui-router to `devDependencies`
