### ISSUE TITLE
Unable to show HTML content on the notification

### ISSUE THREAD

**Issue by harshadbhandure-tudip** [base-apps/angular-base-apps#95]
I am using the `BaseAppsApi.publish` method for displaying the notification and passing the string in `content` field.
But, it is unable to display the html content on notification and displaying the html tags as it is.
I have tried using the `$sce.trustAsHtml` while passing the string but I can't use `ng-bind-html` in view.

I want to display bullet points on notification.
What should be done in order to display the html content on notification?

**Comment by soumak77** [comment]
@harshadbhandure-tudip It looks like injecting HTML is only supported for the notification title.  If you pass the HTML via the `title` property then it should work.  Here is the source: https://github.com/zurb/foundation-apps/blob/b96c3e1d0badd286b356b7b206364454a445388f/js/angular/components/notification/notification.js#L137-L143

One problem with this approach is that the injected html is wrapped in a `h1` tag: https://github.com/zurb/foundation-apps/blob/b96c3e1d0badd286b356b7b206364454a445388f/js/angular/components/notification/notification.html#L9

I think a new `html` property should be introduced which would operate exactly like the `content` property, except it would inject the html into a `div` instead of rendering plain text in a `p` tag.

**Comment by harshadbhandure-tudip** [comment]
@soumak77 
Yes. What should be done in order to format the `content` property?
It is not allowing `\n` to break the line.
Can you please suggest?

**Comment by soumak77** [comment]
@harshadbhandure-tudip I added support for HTML content in v2.0.11.  Check the docs for specific examples: http://base-apps.github.io/angular-base-apps/v2.0.11/#!/notification

**Comment by harshadbhandure-tudip** [comment]
Thank you!
